version: '3.8'

services:
  # 2. Contenedor de la Base de Datos (Persistencia - Sprint 2)
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password_secreto
      - POSTGRES_DB=proyecto_equipo3
    volumes:
      # Esto asegura que los platos, pedidos y usuarios no se borren si apagan Docker
      - pg_data:/var/lib/postgresql/data
      # Autocarga de las tablas del Sprint 2
      - ./bd/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pg_data:
